image: node:10.1.0

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install -g yarn
          - chmod +x /usr/local/bin/yarn
          - yarn install
          - yarn test
