version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./infra/etc/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on:
      - api

  api:
    image: node:10.1.0
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: npm start

